### PR TITLE
Updates `material-ui` dep

### LINKED ISSUE #88: "Uncaught (in promise) TypeError: Cannot read property 'x' of null"
The error is from the terminal while running npm start.

Also the Yeoman app never open and automagically open the dev tool and I saw those errors.

_materialUi2.default.Styles.themeManager is not a function.

in node_modules/less/dist/less.js, xhr.open('GET', url, async); is throwing Synchronous error.

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience.

### PR DESCRIPTION
**Pull request by ruyadorno**
This fixes #88 

please CR @stefanbuck  :blush:

### CODE REVIEW

**Comment by ruyadorno** [comment]
Sorry for the lack of context @stefanbuck, I was trying [livecoding](https://youtu.be/LkdAU_RC0TE) for the first time when I opened the PR.

`material-ui` is a dependency that largely abuses on **semver** magic zero... every once in a while we have to fix some breaking change they pushed into a minor release - this PR just fixes one of these issues.

Also, update React to `0.14.x` :wink:

**Comment by stefanbuck** [comment]
Looks good besides the black "compatibility warning" rectangle after selecting Angular generator.  

screen shot 2015-12-07 at 00 33 20

**Comment by stefanbuck** [comment]
Hi @ruyadorno, I tried to figure out what exactly cause this back rectangle without luck. I'm assume you are more familiar with `material-ui` than me.

**Comment by ruyadorno** [comment]
hi @stefanbuck I pushed a new fix yesterday, have you take a look?

now the only thing left that can use some improvement is that part of the bar remains at screen once you're in a generator that shows the compatibility warning and you dismiss it.

I think we're good to merge this for now, as otherwise the app is broken on master, can you test it again and merge it please?

**Comment by stefanbuck** [comment]
No, not yet. Yeah, let's merge this first and revisit it as you suggested. Thanks for the fix :+1:

**Pull request merged**
