### PR TITLE
Tweak build script to build the app for all platforms

### PR DESCRIPTION
**Pull request by stefanbuck**
Use `npm run package` to build executables for all supported platforms. Use `npm run pack-win` `npm run pack-mac` `npm run pack-linux` to build the executables for a specific platform. When successful, the executables will be located at `./out/`

**Building Windows apps from non-Windows platforms**

Building an Electron app for the Windows platform with a custom icon requires editing the `Electron.exe` file. Currently, electron-packager uses [node-rcedit](https://github.com/atom/node-rcedit) to accomplish this. A Windows executable is bundled in that node package and needs to be run in order for this functionality to work, so on non-Windows platforms, [Wine](https://www.winehq.org/) needs to be installed. On OS X, it is installable via [Homebrew](http://brew.sh/).

@deepu105 Can you please verify if the build script is working on windows?

### CODE REVIEW

**Comment by deepu105** [comment]
Ok ill check

**Comment by stefanbuck** [comment]
The build doesn't work on windows, because the argument paths for `electron-compile` in our `package.json` are not valid with the Linux specific file separator.

Is there any way to define paths in the `package.json` cross platform? @ruyadorno maybe you know something. If not, I guess the only way to deal with it is to use the [programmatic api](http://electronjs.github.io/electron-compile/docs/) of [electron-compile](http://electronjs.github.io/electron-compile/).

**Comment by ruyadorno** [comment]
yeah, no idea :disappointed:

**Comment by stefanbuck** [comment]
I droped https://github.com/sindresorhus/caprine

**Comment by stefanbuck** [comment]
I've dropped the build script and replaced it with a npm scripts for each platform (taken form https://github.com/sindresorhus/caprine) :wink: 

@deepu105 can you please check, if this is working for you?

**Comment by deepu105** [comment]
Ok ill try it out today, hv been busy lately might hv some time today

**Comment by deepu105** [comment]
running `npm run build-windows` gives below error. Sorry dont have much time to debug currently
```
PS D:\Projects\GIT\yeoman-app> npm run build-windows

> yeoman-app@0.0.0 build-windows D:\Projects\GIT\yeoman-app
> electron-packager . $npm_package_productName --overwrite --out=dist --ignore='^/dist$' --ignore='^/resources/(?!app.ico$).*' --prune --platform=win32 --arch=ia32 --icon=resources/app.ico --version=$npm_package_devDependencies_electron_prebuilt --version-string.ProductName=$npm_package_productName
--version-string.ProductVersion=$npm_package_devDependencies_electron_prebuilt && cd dist/Yeoman-win32-ia32/ && zip -ryq9 ../Yeoman-windows-"$npm_package_version".zip *

.*' was unexpected at this time.

D:\Projects\GIT\yeoman-app>  "D:\Projects\GIT\yeoman-app\node_modules\.bin\\node.exe"  "D:\Projects\GIT\yeoman-app\node_modules\.bin\\..\electron-packager\cli.js" . $npm_package_productName --overwrite --out=dist --ignore='/dist$' --ignore='/resources/(?!app.ico$).*' --prune --platform=win32 --arch=ia32 --icon=resources/app.ico --version=$npm_package_devDependencies_electron_prebuilt --version-string.ProductName=$npm_package_productName --version-string.ProductVersion=$npm_package_devDependencies_electron_prebuilt

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Deepu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-windows"
npm ERR! node v5.5.0
npm ERR! npm  v3.7.1
npm ERR! code ELIFECYCLE
npm ERR! yeoman-app@0.0.0 build-windows: `electron-packager . $npm_package_productName --overwrite --out=dist --ignore='^/dist$' --ignore='^/resources/(?!app.ico$).*' --prune --platform=win32 --arch=ia32 --icon=resources/app.ico --version=$npm_package_devDependencies_electron_prebuilt --version-string.ProductName=$npm_package_productName --version-string.ProductVersion=$npm_package_devDependencies_electron_prebuilt && cd dist/Yeoman-win32-ia32/ && zip -ryq9 ../Yeoman-windows-"$npm_package_version".zip *`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the yeoman-app@0.0.0 build-windows script 'electron-packager . $npm_package_productName --overwrite --out=dist --ignore='^/dist$' --ignore='^/resources/(?!app.ico$).*' --prune --platform=win32 --arch=ia32 --icon=resources/app.ico --version=$npm_package_devDependencies_electron_prebuilt --version-string.ProductName=$npm_package_productName --version-string.ProductVersion=$npm_package_devDependencies_electron_prebuilt && cd dist/Yeoman-win32-ia32/ && zip -ryq9 ../Yeoman-windows-"$npm_package_version".zip *'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the yeoman-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-packager . $npm_package_productName --overwrite --out=dist --ignore='^/dist$' --ignore='^/resources/(?!app.ico$).*' --prune --platform=win32 --arch=ia32 --icon=resources/app.ico --version=$npm_package_devDependencies_electron_prebuilt --version-string.ProductName=$npm_package_productName --version-string.ProductVersion=$npm_package_devDependencies_electron_prebuilt && cd dist/Yeoman-win32-ia32/ && zip -ryq9 ../Yeoman-windows-"$npm_package_version".zip *
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs yeoman-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls yeoman-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\GIT\yeoman-app\npm-debug.log
PS D:\Projects\GIT\yeoman-app>
```

**Comment by stefanbuck** [comment]
Can you try this `npm run prebuild && electron-packager . --prune --platform=win32 --arch=ia32`. If this is working for you, please add one by one the args from the npm script build-windows (see `packages.json`)

**Comment by sindresorhus** [comment]
ping @deepu105

**Comment by deepu105** [comment]
Ill try out next week, will be busy till then

**Comment by stefanbuck** [comment]
Thanks @deepu105, will also try to get a windows environment up and running so I can investigate into it as well.

**Comment by stefanbuck** [comment]
Finally, build is working for mac and windows. @ruyadorno you are on linux, right? If so, can you test the build command there, please. `npm run pack-linux`


screen shot 2016-05-25 at 07 53 32

screen shot 2016-05-25 at 07 50 42

**Comment by ruyadorno** [comment]
@stefanbuck I'm actually on OSX too 😕 I do have a ubuntu VirtualBox vm in which I can try to test it later though

**Comment by stefanbuck** [comment]
Strange, I was pretty sure that you are using linux, don't know why 😄 Anyway, VM sounds good. Did the same for the windows build.

**Comment by ruyadorno** [comment]
👍 LGTM

tested on a Ubuntu 15.10 VM ✅

**Pull request merged**
