### PR TITLE
2nd Style update

### PR DESCRIPTION
**Pull request by NuroDev**
Optional change I made that, in my opinion, makes the app look a lot smoother.
Makes the header layered above the main generator content. As well as adding a box shadow to the header.

### CODE REVIEW

**Comment by stefanbuck** [comment]
I like the scrollable content but, I'm undecided about the shadow. Any thoughts on this @ruyadorno?


# Before
before

# After
after

**Comment by stefanbuck** [comment]
@Meadowcottage The header should disappear as soon as a generator is selected. This gives us more space on the next pages for the actual content.

**Comment by ruyadorno** [comment]
hi @Meadowcottage thanks for taking the time to propose this change but in the current format I don't think it's really a good idea to have a fixed header

one thing that could make the fixed position work is to resize the header to make it smaller as we scroll down, but then we would also need to resize the logo and maybe even change it to use the horizontal version: https://github.com/yeoman/media/blob/master/optimized/yeoman-2.svg

here's an example of how I see the sticky header working:
- https://codepen.io/malZiiirA/pen/cbfED

all that said, I don't think the current header image will support that, if we really want to work on an improvement I think it's worth updating it to use the svg assets from: https://github.com/yeoman/media and a solid/plain background

**Comment by Meadowcottage** [comment]
Was just an optional idea I had in mind. Wanted to get some feedback on whether you thought it would be a good feature to implement.

**Comment by ruyadorno** [comment]
@Meadowcottage 👍 sure thing, thank you very much, ideas are always welcomed!

let me know if you have the time to work on the provided feedback 😊

**Comment by Meadowcottage** [comment]
If I get some more free time in the near future I may start work on the feedback you've given. But for now I think I will put this style update on hold.

**Pull request closed without merging**
