### PR TITLE
Added eslint validation

### LINKED ISSUE #65: Adhere to Yeoman styleguide
Bring in JSCS validation from `yeoman-generator`

### PR DESCRIPTION
**Pull request by ruyadorno**
- Adds **eslint** validation to the project.
- Added lint as a `pretest` npm script, so that PRs will fail if code doesn't comply to our standards
- Removed `.jshintrc` and `.jscsrc` as the rules on those might not match a 100% the eslint rules and will be harder to maintain all these standards around
- Style was taken from `generator-node` as suggested by @arthurvr, very minor modifications were made to comply with the use of **React** and **jsx**
- This PR also includes various fixes to normalize the codebase and have `npm run lint` passing

**Ping**:
@stefanbuck my CR buddy
@addyosmani as this was part of his wishlist for 2016

### CODE REVIEW

**Comment by hemanth** [comment]
:+1:

**Comment by stefanbuck** [comment]
Nice one :+1+: Will review it in detail later, but for now one comment / question. I would prefer to have two commits, one for the actually transformation from jshint to eslint and another for fixing. What do you think?

**Comment by addyosmani** [comment]
:+1:

**Comment by ruyadorno** [comment]
@stefanbuck I honestly think it's better to handle it all in a single commit :shipit:

**Comment by mfunkie** [comment]
Awesome, nice job!

**Comment by ruyadorno** [comment]
:confetti_ball:

**Pull request merged**
